-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 20:54:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema colibri
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colibri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colibri` DEFAULT CHARACTER SET utf8 ;
USE `colibri` ;

-- -----------------------------------------------------
-- Table `colibri`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colibri`.`empresa` (
  `id` INT NOT NULL,
  `nit` VARCHAR(20) NULL,
  `nombre` VARCHAR(100) NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colibri`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colibri`.`contacto` (
  `id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  `nombre_contacto` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `telefono` VARCHAR(30) NULL,
  `celular` VARCHAR(30) NULL,
  `cargo` VARCHAR(50) NULL,
  PRIMARY KEY (`id`, `empresa_id`),
  INDEX `fk_contacto_empresa_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_contacto_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `colibri`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
